Add LONG Token on zkSync Era network (Update ERA.json)
lifinance/customized-token-list pull request #123
Opened 2024-11-26 03:14 UTC by ZkSwapFinance

Website: https://long.fun/
Coinmarketcap: https://coinmarketcap.com/currencies/long-fun/
Coingecko: https://www.coingecko.com/en/coins/long-fun

2024-12-23 19:19 UTC, JasnaLiFi approved these changes

2024-12-24 01:34 UTC, myz1237 commented on tokens/ERA.json
> +       "name":"LONG",
According to the debank information, the name is `Long`.

Original return:
```json
{
   "id":"0x5165ec33b491d7b67260b3143f96bb4ac4736398",
   "chain":"era",
   "name":"Long",
   "symbol":"LONG",
   "display_symbol":null,
   "optimized_symbol":"LONG",
   "decimals":18,
   "logo_url":"https://static.debank.com/image/era_token/logo_url/0x5165ec33b491d7b67260b3143f96bb4ac4736398/3e61868b9b13b95a7e6809647050f474.png",
   "protocol_id":"",
   "price":1.4259773351751368e-06,
   "price_24h_change":0.05325374617979149,
   "credit_score":29132.19030253106,
   "is_verified":true,
   "is_scam":false,
   "is_suspicious":false,
   "is_core":true,
   "is_wallet":true,
   "time_at":1711191402.0,
   "low_credit_score":false
}
```

2024-12-24 01:35 UTC, myz1237 commented on tokens/ERA.json
> + ]
please check the format of this bracket

2024-12-24 01:35 UTC, myz1237 requested changes
commented

2024-12-24 06:48 UTC, ZkSwapFinance commented
> commented

Is everything okay? Do we need to create a new PR to change the 'name' field?

2024-12-27 03:15 UTC, myz1237 commented
> > commented
> 
> Is everything okay? Do we need to create a new PR to change the 'name' field?

Could you change it in your pr and push commits here? Change the name and bracket here: 
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/312fd868-ba51-44ad-b372-f802aeecf901" />

Thanks in advance

2024-12-27 03:23 UTC, ZkSwapFinance commented
> > > commented
> > 
> > 
> > Is everything okay? Do we need to create a new PR to change the 'name' field?
> 
> Could you change it in your pr and push commits here? Change the name and bracket here: <img alt="image" width="1225" src="https://private-user-images.githubusercontent.com/54893307/398836711-312fd868-ba51-44ad-b372-f802aeecf901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNzAwNzAsIm5iZiI6MTczNTI2OTc3MCwicGF0aCI6Ii81NDg5MzMwNy8zOTg4MzY3MTEtMzEyZmQ4NjgtYmE1MS00NGFkLWIzNzItZjgwMmFlZWNmOTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAzMjI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNmE2YzdlMTZiNTM1ZDNlZGRhMzQzMmM4Y2E5YjJmOTczODQ1OTZlNTYyNWQ4NWU3YTk0NTY4MjJjNzlmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dFgXRRURUdsN2X_mpZng0uClouMXjsRXT1ST3Py0Id8">
> 
> Thanks in advance

I pushed a new commit with the name field changed. Could you verify it again?

2024-12-27 03:24 UTC, myz1237 approved these changes

2024-12-27 03:24 UTC, merged